### PR TITLE
Optional web Django authentication

### PR DESCRIPTION
**Pull request by pashashocky**
I've been wanting to do this in a neat way for a while, in order not to significantly alter the views code. Previously I've seen it done by turning the whole view into a class like structure. 

- Setting in `web/web/settings.py` to turn Django authentication on/off
- Native Django authentication module 
- Login, Logout templates and admin panel
- Re-written the `url.py` files to not produce errors on `./manage.py runserver`

## Usage 
1. Change `web/web/settings.py:32: WEB_AUTHENTICATION = True`
2. Run `./manage.py migrate`
3. Run `./manage.py createsuperuser`

What do you think?

### CODE REVIEW

**Comment by KillerInstinct** [comment]
+1 for solving Django 1.10 stuff. I never did get around to fully removing the upgrade warnings.

**Comment by pashashocky** [comment]
@KillerInstinct yeah, they bug my OCD. 

Although i am still trying to fix these two warnings:

- `The context_instance argument of render_to_string is deprecated. using=using)`
- `Reversing by dotted path is deprecated (dashboard.views.index).
  url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)`

**Comment by pashashocky** [comment]
This `context_instance argument` warning seems to be related to using `render()` instead of `render_to_response()`

https://docs.djangoproject.com/en/1.9/topics/http/shortcuts/#render-to-response

**Comment by pashashocky** [comment]
2 previously mentioned deprication bugs have been fixed. 

Anything else I can do? @KillerInstinct

**Pull request merged**
