### PR TITLE
Added machinery support for AWS based analysis

### PR DESCRIPTION
**Pull request by veyesecurity**
Hey,
I propose to use AWS for sample analysis. I did not write the detailed tutorial at this moment (but will in following days). 

We are planing to use such deployment in-house as a base for malware analysis lab. I assume that this could be beneficial to others in the community.

Comments are welcome. 

Yevgeniy

### CODE REVIEW

**Comment by KillerInstinct** [comment]
Whats the designed architecture for this? I had seen some people asking about this in IRC, but it was shot down if I remember correctly.

I assume its one of the two:
1) Rent multiple AWS VM's, use one as the ResultsServer and others as the guest VMs -- sharing all the data "internally" 
2) Just rent VMs for guest VMs and results server data gets sent over the internet/VPN back home to a server you run for processing/mongodb'ing.

Do you know how scaleable this is? (EG will your documentation include if its been well tested with 5+ VMs) Assuming it's as scaleable as you have money, but I am unfamiliar with EC2's API and it's potential bottlenecks.

**Comment by veyesecurity** [comment]
In general it goes like this:
 - Prepare AWS vms (instances) without attached volumes in preconfigured VPC with appropriate firewall rules (Network Policies).
 - Prepare snapshot which is a clean one and will be converted to volume and attached to each vm (instance) before sample analysis.

So based on the above logic 1) and 2) are available. The only difference is that 2) will require installed vpn client inside the vm to return results back home.

As to scalability, this is exactly as you mentioned, add more machines according the the budget.

Current drawback of such method is that I did not added the capability to sniff traffic. I'm planing to use `netmon` for that.

**Comment by veyesecurity** [comment]
Hey, 
as I'm relatively new to development of cuckoo, I'm wandering if I can discuss several issues with you and Brad over email. I've further enhanced the AWS machinery module and we are already using it in production. So I think this really could be of help to the community.

Thanks.

**Comment by spender-sandbox** [comment]
Sure, feel free to email me at spender@grsecurity.net

Thanks,
-Brad

**Comment by jgajek** [comment]
I have also been asked about AWS support for Cuckoo and had been thinking about developing a machinery module using the boto API.  If there is one already, it would definitely be useful.

**Comment by veyesecurity** [comment]
We have developed one and already using in our testing environment for a week. It works great for now. I'm currently in the process of refinement and documentation preparation.

It is indeed base on boto API. One of my questions is whether it will be beneficial to anybody,  and it looks it will :-)

**Pull request closed without merging**
