### PR TITLE
Added PEFile and Digital Signature Fixes

### PR DESCRIPTION
**Pull request by keithjjones**
Added fixes for topics discussed in Issue #278 

This PR should allow for static HTML (detailed and summary) to output signature information from static analysis.

### CODE REVIEW

**Comment by spender-sandbox** [comment]
Can you remove the first change?  We don't want people installing whatever the latest pefile is, since it's a constant source of problems as they go through code churn without caring about backward compatibility.

-Brad

**Comment by keithjjones** [comment]
There you go @spender-sandbox 

It matches the master copy now.

**Comment by keithjjones** [comment]
Note that the requirements.txt file is broken in this state as that code isn't there anymore.  You could also require pefile2 if you wanted the older version.

**Comment by spender-sandbox** [comment]
Is it still imported via pefile, or did they change it to pefile2 also?

-Brad

**Comment by jgajek** [comment]
FWIW, I raised an issue on the pefile repo for this (https://github.com/erocarrera/pefile/issues/139).  Silently changing the behavior of a public-facing, documented functions out from under people is simply ridiculous.

**Pull request merged**
