### PR TITLE
KVMRemote machinery for parallel analysis using multiple hypervisors

### PR DESCRIPTION
**Pull request by psrok1**

### CODE REVIEW

**Comment by spender-sandbox** [comment]
Thanks!

How does this deal with pcap acquisition if the KVM instance is on a separate system (as we run tcpdump locally) ?

-Brad

**Comment by mak** [comment]
The easiest way, and the one we are implementing, is to create a span port, and assign it to separate interface on machine with cuckoo

**Comment by doomedraven** [comment]
@mak but is when you have all your servers near one to another, but if they hoster in datacenter and you don't have access is not very useful, but idea is great if you have all of them in local/access to datacenter  servers

**Comment by mak** [comment]
@doomedraven that's true, tbh that's the only setup i considered (when you have all of your's servers nearby).
Also  think they always have to be in the same vlan, since result server have to be reachable from VMs
I think remote acquisition of pcaps  can be solved by tcpdump wrapper and ssh to remote libvirt server

**Comment by doomedraven** [comment]
is why im finishing distributed part :)
but both solution working and good depending on where your servers placed

**Comment by doomedraven** [comment]
there also bottleneck in processing(consuming much cpu) and depend of your processing/reporting options take a while or take nothing, you analyse it in vms and later it generates reports(same server), but in that setup(remove hypervisor) you must also have super server to handle all load

**Comment by mak** [comment]
@doomedraven looking forward to it ;]
as for bottleneck, yeah i guess that may be a problem, but hmm i wouldn't worry about it that much,
processing i quite atomic so you can pack your analysis and send somewhere else ;]

**Comment by doomedraven** [comment]
@mak yes you can send it, but still the same problem, speed of data transferring(imagine 2gb memdump, pcaps, etc etc etc) if not in the same vlan, is what im trying to solve in distributed, and link that data in some way, the core is working, i just retrieve mongo report to store in master server as max size is only up to 16mb, and gzipped much less, i can have my kind of "super server".

but is my personal problem :) i would be happy see your and my solution to be accepted :P

**Comment by spender-sandbox** [comment]
Why not base it around a model of a NFS share mounted on separate web / mongo / processing / VM servers?  With a local 10gbps link I think it would be okay and would make the implementation quite close to running everything on the same system.

-Brad

**Comment by doomedraven** [comment]
it was my initial idea, nfs all the things, but then we was faced with another problem, not remember exactly which one right now %)

**Pull request merged**
