### PR TITLE
WSGI Default Config

### PR DESCRIPTION
**Pull request by geudrik**
This change is really an ease of use change. There's literally zero reason not to utilize WSGI, so this makes setup all that much easier. One need only read the comments in `web/web/wsgi.py` to get up and running.

### CODE REVIEW

**Comment by KillerInstinct** [comment]
Can confirm that this breaks nginx.

**Comment by geudrik** [comment]
Good catch @KillerInstinct. Not sure why that didn't puke on my end... Does this fix the nginx breakage?

**Comment by KillerInstinct** [comment]
It does! The actual virtual config wasn't the problem, only those imports.

**Comment by geudrik** [comment]
Cool, good to hear I didn't royally screw things up :)

**Pull request merged**
