### PR TITLE
- Add Payload delivery hash to misp about the details of the analyzed file

### PR DESCRIPTION
**Pull request by SteveClement**
- Add Payload delivery hash to misp about the details of the analyzed file

### CODE REVIEW

**Comment by doomedraven** [comment]
tnx, now is time to remove, as basic target info already was there

```
        if results.get("target", {}).get("file", {}).get("md5", "") and results["target"]["file"]["md5"] not in whitelist:
            self.iocs.append(results["target"]["file"]["md5"])
            iocs.append({"md5": results["target"]["file"]["md5"]})
            filtered_iocs.append(results["target"]["file"]["md5"])

        if results.get("target", {}).get("file", {}).get("sha1", "") and results["target"]["file"]["sha1"] not in whitelist:
            self.iocs.append(results["target"]["file"]["sha1"])
            iocs.append({"sha1": results["target"]["file"]["sha1"]})
            filtered_iocs.append(results["target"]["file"]["sha1"])
```

**Comment by SteveClement** [comment]
Thanks. On a related not.

@jbremer the MISP Module in the main cuckoo repo, @doomedraven used this as a basis I think. Could we synch the -modified misp module into the main cuckoo repo?

**Comment by doomedraven** [comment]
we can for sure :)
but i need first improve the iocs upload with bulk upload, to not push one by one, as now is implemented :)

**Comment by SteveClement** [comment]
Ok cool. I will do one more little beauty tweak with the 3 add_hashes lines into: 

            if ioc.get("md5", ""):
                self.misp.add_hashes(event, md5=ioc["md5"], sha1=ioc["sha1"], sha256=ioc["sha256"])

Supposing that there will always be the other hashes if an md5 hash exists.

**Comment by doomedraven** [comment]
@SteveClement https://github.com/spender-sandbox/cuckoo-modified/pull/197 updated
the misp plugin in main cuckoo based on mine one(this)

**Pull request merged**
