### PR TITLE
misp integration extended to store report

### PR DESCRIPTION
**Pull request by doomedraven**
as @seanthegeek  requested, added possibility to store full misp report
not only part for webgui

### CODE REVIEW

**Comment by doomedraven** [comment]
screen shot 2016-05-15 at 00 30 32

**Comment by doomedraven** [comment]
@brad-accuvant can you check this?

**Comment by spender-sandbox** [comment]
Wrong account ;)  And the PR has conflicts I'll have to resolve, so I'll do this on Monday.

-Brad

**Comment by doomedraven** [comment]
@spender-sandbox solved :)

**Comment by spender-sandbox** [comment]
The double config entries is a little weird, and it's not standard for us to have an entry in reporting.conf that doesn't correspond to an actual reporting module.  Could the actual JSON conversion of the MISP report be split off into its own module?  Then you could also get rid of the extra option in the processing entry.

-Brad

**Comment by doomedraven** [comment]
@spender-sandbox the problem is if I move it to reporting module I can't store it to default container with all results to draw results in webgui, or any point how to do that?

**Comment by spender-sandbox** [comment]
How much data do you expect the full report to have?  It can't all simply be added to the results dict with the report just being a json version of it?

-Brad

**Comment by doomedraven** [comment]
is depending on the number of iocs which you have in analysis(IPs, domains, md5s) and in how many events they found, and then it also contains a bit of information about all iocs in that events, 

for me personally is better contain short description in webgui then just have link to download json report(i did this for @seanthegeek ), as there event id as url so it can be opened quickly and it more easier to recognize where that malware what used and related stuff to those iocs

so if there no way to add data to global results container from reports to draw web, I think lets close this and keep that as it already was integrated webgui part

screen shot 2016-05-15 at 14 19 27

**Comment by spender-sandbox** [comment]
You can modify the reports dict from reporting modules, that was something I added.  The order on mongodb is set very high so it'll make use of any changes there.  If the goal isn't to have any signatures or anything else act on the MISP information, then doing the entire thing as a reporting module would indeed be the thing to do.

-Brad

**Comment by doomedraven** [comment]
@spender-sandbox thanks for pointing me, i will play around and return to this with update of code :)

**Comment by doomedraven** [comment]
@spender-sandbox hm I cheked the reporting class in abstracts https://github.com/spender-sandbox/cuckoo-modified/blob/master/lib/cuckoo/common/abstracts.py#L1340 and i don't see way to add it, also tried to add `{"MISP":mis_results}` to general results dict and return it but no way to get it in final report.json

any point?

**Comment by spender-sandbox** [comment]
Each reporting module's run method takes an argument of the results dict.  Modifying that should modify the same results dict used by later reporting modules.

-Brad

**Comment by doomedraven** [comment]
hm look

in `def run(self, reports)`
i have self.key = "misp" so theorically it would create key in general dict
and then at the end i have 

```
pre_results = sorted(self.misper.values(), key=lambda x: datetime.strptime(x["date"], "%Y-%m-%d"), reverse=True)
results.update({"MISP": pre_results}) # with and without this line no difference
log.info(str(results.keys()))
log.info(str(results["MISP"]))
return results # with and without return no difference
```

and in logs i can see

```
2016-05-15 15:15:03,515 [modules.reporting.misp] INFO: ['info', 'signatures', 'statistics', 'network', 'suricata', 'malfamily', 'virustotal', 'malscore', 'procmemory', 'decompression', 'dropped', 'behavior', 'debug', 'static', 'feeds', 'MISP', 'strings', 'target'] <- before return
2016-05-15 15:15:03,516 [modules.reporting.misp] INFO: [{'info': u'ranger89r | Malc0de IP Blacklist', 'level': u'4', 'url': 'https://intel.ecrime.io/events/view/', 'iocs': ['58.218.211.172'], 'eid': u'3727', 'date': u'2016-02-11'}]
```

sorry for boring you with this, just can't find the way to make it works

**Comment by spender-sandbox** [comment]
I don't believe the self.key is valid for reporting modules.

You'd just do:
results["misp"] = blah

and no need to return anything

-Brad

**Comment by doomedraven** [comment]
@brad-accuvant wtf :D how is possible what `results["misp"] = pre_results` works and `results.update({"misp": pre_results})` nop xD

working now

one last quesiton

* web/templates/analysis/reports/index.html

if i checking `config.misp.reporting`, which is set to yes is not shown in webgui

```
      {% if config.misp.reporting %}
        <tr>
            <th>MISP Report</th>
            <td style="text-align: right;"><a class="btn btn-primary btn-small" href="{% url "analysis.views.filereport" analysis.info.id "misp" %}">Download</a></td>
        </tr>
      {% endif %}
```

* but if i adding new conf bloc as this it works

```
[reportmisp]
enabled = yes

and change in html
   {% if config.misp.reporting %}
to
   {% if config.reportmisp%}
```

### misp config

```
[misp]
enabled = yes
apikey = apikey
url = url
threads = 10
reporting = yes
```

printing whole config i can see 
 'misp': False, 
'reportmisp': True,

* So put both or how i can trick it to make it works?

**Comment by spender-sandbox** [comment]
IIRC the config info is pushed out from views.py -- it doesn't automatically grab everything, so you'd have to add some code near the top of it to allow templates to see that config entry.

-Brad

**Comment by doomedraven** [comment]
ok now its done :)

**Comment by spender-sandbox** [comment]
Need to fix a few things in this, but will pull it for now and fix those up.

-Brad

**Comment by doomedraven** [comment]
ok thanks, let me know if i can fix it quickly for you

**Pull request merged**
